### ISSUE TITLE
Doing 5 damage to Flier

### ISSUE THREAD

**Issue by sand-undertale** [KockaAdmiralac/uty-save-editor#11] opened 2024-01-28 05:40 UTC
When doing a genocide route, I set all my stats to 9999999999999999999999 and gave myself friendliness pellets and yet I still do 5 damage to flier, did I set the values to high or is this a bug? [[NOTE]] I set myself to LV.20 but then I killed a Flier I went to LV.21.

**Comment by KockaAdmiralac** [comment] 2024-01-28 08:07
So, you set your stats very high, killed a Flier immediately, advanced to LV21 and then were dealing 5HP damages to Fliers? If so, then no, that's not a bug: the game must have reset all your stats to 0 because it can't find any stats for LV21. Can you load your save into the editor again and check your stats? Also, can you send you save file here, too?

**Comment by sand-undertale** [comment] 2024-01-28 16:47
That was the problem, there is no values except defense at LV.21, thank you!

[[It's not letting me send .sav files.]]

**Comment by sand-undertale** [comment] 2024-01-28 16:53
Also, something cool/weird that happened was it put me back on a pacifist route I did before the reset, so I guess Save02.sav was my genocide path.

**Comment by KockaAdmiralac** [comment] 2024-05-12 16:36
Closing this as completed, since the original issue seems to be resolved.

**Closed as completed by KockaAdmiralac** 2024-05-12 16:36 UTC
